version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    links:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - CURRENCY_API_KEY=set-valid-api-key-here
